apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
  labels:
    type: onpem
spec:
  storageClassName: mysql-db
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.138.71.9
    path: "/var/Kubernetes-Volumes/1"
